// Generated by CoffeeScript 1.12.2
(function() {
  var geturl;

  geturl = function(url, callback) {
    var encoded;
    encoded = encodeURIComponent(url);
    return $.ajax({
      url: window.location.origin + '/geturl',
      data: {
        url: encoded
      },
      success: function(response) {
        return callback(response);
      }
    });
  };

  $(function() {
    var markov;
    markov = new MarkovChain("");
    markov.setup(function() {
      var generate;
      generate = function() {
        var text;
        text = markov.generate(5);
        if (text !== "") {
          return $('#output ul').prepend($("<li>" + text + "</li>"));
        }
      };
      return setInterval(generate, 1000);
    });
    return $('form#url_form').on('submit', function(e) {
      var url;
      e.preventDefault();
      console.log($(this));
      window.x = $(this);
      url = $(this).serializeArray()[0].value;
      console.log(url);
      $('#input ul').prepend($("<li>" + url + "</li>"));
      geturl(url, function(res) {
        var elem, i, len, ref, results, text;
        console.log(res);
        ref = $(res).find('p, a, h1, h2, h3, li');
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          elem = ref[i];
          text = $(elem).text();
          console.log(text);
          results.push(markov.addText(text));
        }
        return results;
      });
      return $('form#url_form input').val(null);
    });
  });

}).call(this);
