// Generated by CoffeeScript 1.12.2
(function() {
  var geturl;

  geturl = function(url, callback) {
    var encoded;
    encoded = encodeURIComponent(url);
    return $.ajax({
      url: window.location.origin + '/geturl',
      data: {
        url: encoded
      },
      success: function(response) {
        return callback(response);
      }
    });
  };

  $(function() {
    var markov;
    markov = new MarkovChain("");
    markov.setup(function() {
      var generate;
      generate = function() {
        var text;
        text = markov.generate(5);
        if (text !== "") {
          return $('#output ul').prepend($("<li>" + text + "</li>"));
        }
      };
      return setInterval(generate, 1000);
    });
    return $('form#url_form').on('submit', function(e) {
      var url;
      e.preventDefault();
      window.x = $(this);
      url = $(this).serializeArray()[0].value;
      $('#input ul').prepend($("<li>" + url + "</li>"));
      console.log('fuhe');
      geturl(url, function(res) {
        var jtext, text;
        text = $(res).text();
        jtext = text.match(/[^\x00-\x7E]+/g).join("");
        console.log(jtext);
        return markov.addText(jtext);
      });
      return $('form#url_form input').val(null);
    });
  });

}).call(this);
